version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tool
    ports:
      - '4060:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
###< doctrine/doctrine-bundle ###
###> php:7.4-fpm ###
  php:
    container_name: php
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/pinguis
    ports:
      - '9000:9000'
    depends_on:
      - database
###< php:7.4-fpm ###
###> nginx ###
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/pinguis
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
###< nginx ###